# uncompyle6 version 3.9.0
# Python bytecode version base 2.7 (62211)
# Decompiled from: Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)]
# Embedded file name: C:\TeamCity\buildAgent\work\dc8eb0b1d2cf198a\Main\client\standalone\build\pyi.win32\run_obfuscated\out00-PYZ.pyz\pyglet.gl.wglext_arb
__docformat__ = 'restructuredtext'
__version__ = '$Id: gengl.py 601 2007-02-04 05:36:59Z Alex.Holkner $'
from ..ctypes import *
from pyglet.gl.lib import link_WGL as _link_function
from pyglet.gl.lib import c_ptrdiff_t, c_void
WIN32_LEAN_AND_MEAN = 1
WGL_WGLEXT_VERSION = 11
WGL_FRONT_COLOR_BUFFER_BIT_ARB = 1
WGL_BACK_COLOR_BUFFER_BIT_ARB = 2
WGL_DEPTH_BUFFER_BIT_ARB = 4
WGL_STENCIL_BUFFER_BIT_ARB = 8
WGL_SAMPLE_BUFFERS_ARB = 8257
WGL_SAMPLES_ARB = 8258
WGL_NUMBER_PIXEL_FORMATS_ARB = 8192
WGL_DRAW_TO_WINDOW_ARB = 8193
WGL_DRAW_TO_BITMAP_ARB = 8194
WGL_ACCELERATION_ARB = 8195
WGL_NEED_PALETTE_ARB = 8196
WGL_NEED_SYSTEM_PALETTE_ARB = 8197
WGL_SWAP_LAYER_BUFFERS_ARB = 8198
WGL_SWAP_METHOD_ARB = 8199
WGL_NUMBER_OVERLAYS_ARB = 8200
WGL_NUMBER_UNDERLAYS_ARB = 8201
WGL_TRANSPARENT_ARB = 8202
WGL_TRANSPARENT_RED_VALUE_ARB = 8247
WGL_TRANSPARENT_GREEN_VALUE_ARB = 8248
WGL_TRANSPARENT_BLUE_VALUE_ARB = 8249
WGL_TRANSPARENT_ALPHA_VALUE_ARB = 8250
WGL_TRANSPARENT_INDEX_VALUE_ARB = 8251
WGL_SHARE_DEPTH_ARB = 8204
WGL_SHARE_STENCIL_ARB = 8205
WGL_SHARE_ACCUM_ARB = 8206
WGL_SUPPORT_GDI_ARB = 8207
WGL_SUPPORT_OPENGL_ARB = 8208
WGL_DOUBLE_BUFFER_ARB = 8209
WGL_STEREO_ARB = 8210
WGL_PIXEL_TYPE_ARB = 8211
WGL_COLOR_BITS_ARB = 8212
WGL_RED_BITS_ARB = 8213
WGL_RED_SHIFT_ARB = 8214
WGL_GREEN_BITS_ARB = 8215
WGL_GREEN_SHIFT_ARB = 8216
WGL_BLUE_BITS_ARB = 8217
WGL_BLUE_SHIFT_ARB = 8218
WGL_ALPHA_BITS_ARB = 8219
WGL_ALPHA_SHIFT_ARB = 8220
WGL_ACCUM_BITS_ARB = 8221
WGL_ACCUM_RED_BITS_ARB = 8222
WGL_ACCUM_GREEN_BITS_ARB = 8223
WGL_ACCUM_BLUE_BITS_ARB = 8224
WGL_ACCUM_ALPHA_BITS_ARB = 8225
WGL_DEPTH_BITS_ARB = 8226
WGL_STENCIL_BITS_ARB = 8227
WGL_AUX_BUFFERS_ARB = 8228
WGL_NO_ACCELERATION_ARB = 8229
WGL_GENERIC_ACCELERATION_ARB = 8230
WGL_FULL_ACCELERATION_ARB = 8231
WGL_SWAP_EXCHANGE_ARB = 8232
WGL_SWAP_COPY_ARB = 8233
WGL_SWAP_UNDEFINED_ARB = 8234
WGL_TYPE_RGBA_ARB = 8235
WGL_TYPE_COLORINDEX_ARB = 8236
ERROR_INVALID_PIXEL_TYPE_ARB = 8259
ERROR_INCOMPATIBLE_DEVICE_CONTEXTS_ARB = 8276
WGL_DRAW_TO_PBUFFER_ARB = 8237
WGL_MAX_PBUFFER_PIXELS_ARB = 8238
WGL_MAX_PBUFFER_WIDTH_ARB = 8239
WGL_MAX_PBUFFER_HEIGHT_ARB = 8240
WGL_PBUFFER_LARGEST_ARB = 8243
WGL_PBUFFER_WIDTH_ARB = 8244
WGL_PBUFFER_HEIGHT_ARB = 8245
WGL_PBUFFER_LOST_ARB = 8246
WGL_BIND_TO_TEXTURE_RGB_ARB = 8304
WGL_BIND_TO_TEXTURE_RGBA_ARB = 8305
WGL_TEXTURE_FORMAT_ARB = 8306
WGL_TEXTURE_TARGET_ARB = 8307
WGL_MIPMAP_TEXTURE_ARB = 8308
WGL_TEXTURE_RGB_ARB = 8309
WGL_TEXTURE_RGBA_ARB = 8310
WGL_NO_TEXTURE_ARB = 8311
WGL_TEXTURE_CUBE_MAP_ARB = 8312
WGL_TEXTURE_1D_ARB = 8313
WGL_TEXTURE_2D_ARB = 8314
WGL_MIPMAP_LEVEL_ARB = 8315
WGL_CUBE_MAP_FACE_ARB = 8316
WGL_TEXTURE_CUBE_MAP_POSITIVE_X_ARB = 8317
WGL_TEXTURE_CUBE_MAP_NEGATIVE_X_ARB = 8318
WGL_TEXTURE_CUBE_MAP_POSITIVE_Y_ARB = 8319
WGL_TEXTURE_CUBE_MAP_NEGATIVE_Y_ARB = 8320
WGL_TEXTURE_CUBE_MAP_POSITIVE_Z_ARB = 8321
WGL_TEXTURE_CUBE_MAP_NEGATIVE_Z_ARB = 8322
WGL_FRONT_LEFT_ARB = 8323
WGL_FRONT_RIGHT_ARB = 8324
WGL_BACK_LEFT_ARB = 8325
WGL_BACK_RIGHT_ARB = 8326
WGL_AUX0_ARB = 8327
WGL_AUX1_ARB = 8328
WGL_AUX2_ARB = 8329
WGL_AUX3_ARB = 8330
WGL_AUX4_ARB = 8331
WGL_AUX5_ARB = 8332
WGL_AUX6_ARB = 8333
WGL_AUX7_ARB = 8334
WGL_AUX8_ARB = 8335
WGL_AUX9_ARB = 8336
WGL_TYPE_RGBA_FLOAT_ARB = 8608
WGL_CONTEXT_DEBUG_BIT_ARB = 1
WGL_CONTEXT_FORWARD_COMPATIBLE_BIT_ARB = 2
WGL_CONTEXT_MAJOR_VERSION_ARB = 8337
WGL_CONTEXT_MINOR_VERSION_ARB = 8338
WGL_CONTEXT_LAYER_PLANE_ARB = 8339
WGL_CONTEXT_FLAGS_ARB = 8340
ERROR_INVALID_VERSION_ARB = 8341
ERROR_INVALID_PIXEL_TYPE_EXT = 8259
WGL_NUMBER_PIXEL_FORMATS_EXT = 8192
WGL_DRAW_TO_WINDOW_EXT = 8193
WGL_DRAW_TO_BITMAP_EXT = 8194
WGL_ACCELERATION_EXT = 8195
WGL_NEED_PALETTE_EXT = 8196
WGL_NEED_SYSTEM_PALETTE_EXT = 8197
WGL_SWAP_LAYER_BUFFERS_EXT = 8198
WGL_SWAP_METHOD_EXT = 8199
WGL_NUMBER_OVERLAYS_EXT = 8200
WGL_NUMBER_UNDERLAYS_EXT = 8201
WGL_TRANSPARENT_EXT = 8202
WGL_TRANSPARENT_VALUE_EXT = 8203
WGL_SHARE_DEPTH_EXT = 8204
WGL_SHARE_STENCIL_EXT = 8205
WGL_SHARE_ACCUM_EXT = 8206
WGL_SUPPORT_GDI_EXT = 8207
WGL_SUPPORT_OPENGL_EXT = 8208
WGL_DOUBLE_BUFFER_EXT = 8209
WGL_STEREO_EXT = 8210
WGL_PIXEL_TYPE_EXT = 8211
WGL_COLOR_BITS_EXT = 8212
WGL_RED_BITS_EXT = 8213
WGL_RED_SHIFT_EXT = 8214
WGL_GREEN_BITS_EXT = 8215
WGL_GREEN_SHIFT_EXT = 8216
WGL_BLUE_BITS_EXT = 8217
WGL_BLUE_SHIFT_EXT = 8218
WGL_ALPHA_BITS_EXT = 8219
WGL_ALPHA_SHIFT_EXT = 8220
WGL_ACCUM_BITS_EXT = 8221
WGL_ACCUM_RED_BITS_EXT = 8222
WGL_ACCUM_GREEN_BITS_EXT = 8223
WGL_ACCUM_BLUE_BITS_EXT = 8224
WGL_ACCUM_ALPHA_BITS_EXT = 8225
WGL_DEPTH_BITS_EXT = 8226
WGL_STENCIL_BITS_EXT = 8227
WGL_AUX_BUFFERS_EXT = 8228
WGL_NO_ACCELERATION_EXT = 8229
WGL_GENERIC_ACCELERATION_EXT = 8230
WGL_FULL_ACCELERATION_EXT = 8231
WGL_SWAP_EXCHANGE_EXT = 8232
WGL_SWAP_COPY_EXT = 8233
WGL_SWAP_UNDEFINED_EXT = 8234
WGL_TYPE_RGBA_EXT = 8235
WGL_TYPE_COLORINDEX_EXT = 8236
WGL_DRAW_TO_PBUFFER_EXT = 8237
WGL_MAX_PBUFFER_PIXELS_EXT = 8238
WGL_MAX_PBUFFER_WIDTH_EXT = 8239
WGL_MAX_PBUFFER_HEIGHT_EXT = 8240
WGL_OPTIMAL_PBUFFER_WIDTH_EXT = 8241
WGL_OPTIMAL_PBUFFER_HEIGHT_EXT = 8242
WGL_PBUFFER_LARGEST_EXT = 8243
WGL_PBUFFER_WIDTH_EXT = 8244
WGL_PBUFFER_HEIGHT_EXT = 8245
WGL_DEPTH_FLOAT_EXT = 8256
WGL_SAMPLE_BUFFERS_3DFX = 8288
WGL_SAMPLES_3DFX = 8289
WGL_SAMPLE_BUFFERS_EXT = 8257
WGL_SAMPLES_EXT = 8258
WGL_DIGITAL_VIDEO_CURSOR_ALPHA_FRAMEBUFFER_I3D = 8272
WGL_DIGITAL_VIDEO_CURSOR_ALPHA_VALUE_I3D = 8273
WGL_DIGITAL_VIDEO_CURSOR_INCLUDED_I3D = 8274
WGL_DIGITAL_VIDEO_GAMMA_CORRECTED_I3D = 8275
WGL_GAMMA_TABLE_SIZE_I3D = 8270
WGL_GAMMA_EXCLUDE_DESKTOP_I3D = 8271
WGL_GENLOCK_SOURCE_MULTIVIEW_I3D = 8260
WGL_GENLOCK_SOURCE_EXTENAL_SYNC_I3D = 8261
WGL_GENLOCK_SOURCE_EXTENAL_FIELD_I3D = 8262
WGL_GENLOCK_SOURCE_EXTENAL_TTL_I3D = 8263
WGL_GENLOCK_SOURCE_DIGITAL_SYNC_I3D = 8264
WGL_GENLOCK_SOURCE_DIGITAL_FIELD_I3D = 8265
WGL_GENLOCK_SOURCE_EDGE_FALLING_I3D = 8266
WGL_GENLOCK_SOURCE_EDGE_RISING_I3D = 8267
WGL_GENLOCK_SOURCE_EDGE_BOTH_I3D = 8268
WGL_IMAGE_BUFFER_MIN_ACCESS_I3D = 1
WGL_IMAGE_BUFFER_LOCK_I3D = 2
WGL_BIND_TO_TEXTURE_DEPTH_NV = 8355
WGL_BIND_TO_TEXTURE_RECTANGLE_DEPTH_NV = 8356
WGL_DEPTH_TEXTURE_FORMAT_NV = 8357
WGL_TEXTURE_DEPTH_COMPONENT_NV = 8358
WGL_DEPTH_COMPONENT_NV = 8359
WGL_BIND_TO_TEXTURE_RECTANGLE_RGB_NV = 8352
WGL_BIND_TO_TEXTURE_RECTANGLE_RGBA_NV = 8353
WGL_TEXTURE_RECTANGLE_NV = 8354
WGL_TYPE_RGBA_FLOAT_ATI = 8608
WGL_FLOAT_COMPONENTS_NV = 8368
WGL_BIND_TO_TEXTURE_RECTANGLE_FLOAT_R_NV = 8369
WGL_BIND_TO_TEXTURE_RECTANGLE_FLOAT_RG_NV = 8370
WGL_BIND_TO_TEXTURE_RECTANGLE_FLOAT_RGB_NV = 8371
WGL_BIND_TO_TEXTURE_RECTANGLE_FLOAT_RGBA_NV = 8372
WGL_TEXTURE_FLOAT_R_NV = 8373
WGL_TEXTURE_FLOAT_RG_NV = 8374
WGL_TEXTURE_FLOAT_RGB_NV = 8375
WGL_TEXTURE_FLOAT_RGBA_NV = 8376
WGL_STEREO_EMITTER_ENABLE_3DL = 8277
WGL_STEREO_EMITTER_DISABLE_3DL = 8278
WGL_STEREO_POLARITY_NORMAL_3DL = 8279
WGL_STEREO_POLARITY_INVERT_3DL = 8280
WGL_TYPE_RGBA_UNSIGNED_FLOAT_EXT = 8360
WGL_FRAMEBUFFER_SRGB_CAPABLE_EXT = 8361
WGL_NUM_VIDEO_SLOTS_NV = 8432
WGL_BIND_TO_VIDEO_RGB_NV = 8384
WGL_BIND_TO_VIDEO_RGBA_NV = 8385
WGL_BIND_TO_VIDEO_RGB_AND_DEPTH_NV = 8386
WGL_VIDEO_OUT_COLOR_NV = 8387
WGL_VIDEO_OUT_ALPHA_NV = 8388
WGL_VIDEO_OUT_DEPTH_NV = 8389
WGL_VIDEO_OUT_COLOR_AND_ALPHA_NV = 8390
WGL_VIDEO_OUT_COLOR_AND_DEPTH_NV = 8391
WGL_VIDEO_OUT_FRAME = 8392
WGL_VIDEO_OUT_FIELD_1 = 8393
WGL_VIDEO_OUT_FIELD_2 = 8394
WGL_VIDEO_OUT_STACKED_FIELDS_1_2 = 8395
WGL_VIDEO_OUT_STACKED_FIELDS_2_1 = 8396
WGL_ERROR_INCOMPATIBLE_AFFINITY_MASKS_NV = 8400
WGL_ERROR_MISSING_AFFINITY_MASK_NV = 8401
HANDLE = POINTER(None)
HPBUFFERARB = HANDLE
HPBUFFEREXT = HANDLE
HVIDEOOUTPUTDEVICENV = HANDLE
HPVIDEODEV = HANDLE
HPGPUNV = HANDLE
HGPUNV = HANDLE

class struct__GPU_DEVICE(Structure):
    __slots__ = [
     'cb', 
     'DeviceName', 
     'DeviceString', 
     'Flags', 
     'rcVirtualScreen']


DWORD = c_ulong
CHAR = c_char

class struct_tagRECT(Structure):
    __slots__ = [
     'left',
     'top',
     'right',
     'bottom']


LONG = c_long
struct_tagRECT._fields_ = [
 (
  'left', LONG),
 (
  'top', LONG),
 (
  'right', LONG),
 (
  'bottom', LONG)]
RECT = struct_tagRECT
struct__GPU_DEVICE._fields_ = [
 (
  'cb', DWORD),
 (
  'DeviceName', CHAR * 32),
 (
  'DeviceString', CHAR * 128),
 (
  'Flags', DWORD),
 (
  'rcVirtualScreen', RECT)]
GPU_DEVICE = struct__GPU_DEVICE
PGPU_DEVICE = POINTER(struct__GPU_DEVICE)
WGL_ARB_buffer_region = 1
HDC = HANDLE
UINT = c_uint
wglCreateBufferRegionARB = _link_function('wglCreateBufferRegionARB', HANDLE, [HDC, c_int, UINT], 'ARB_buffer_region')
VOID = None
wglDeleteBufferRegionARB = _link_function('wglDeleteBufferRegionARB', VOID, [HANDLE], 'ARB_buffer_region')
BOOL = c_long
wglSaveBufferRegionARB = _link_function('wglSaveBufferRegionARB', BOOL, [HANDLE, c_int, c_int, c_int, c_int], 'ARB_buffer_region')
wglRestoreBufferRegionARB = _link_function('wglRestoreBufferRegionARB', BOOL, [HANDLE, c_int, c_int, c_int, c_int, c_int, c_int], 'ARB_buffer_region')
PFNWGLCREATEBUFFERREGIONARBPROC = CFUNCTYPE(HANDLE, HDC, c_int, UINT)
PFNWGLDELETEBUFFERREGIONARBPROC = CFUNCTYPE(VOID, HANDLE)
PFNWGLSAVEBUFFERREGIONARBPROC = CFUNCTYPE(BOOL, HANDLE, c_int, c_int, c_int, c_int)
PFNWGLRESTOREBUFFERREGIONARBPROC = CFUNCTYPE(BOOL, HANDLE, c_int, c_int, c_int, c_int, c_int, c_int)
WGL_ARB_multisample = 1
WGL_ARB_extensions_string = 1
wglGetExtensionsStringARB = _link_function('wglGetExtensionsStringARB', c_char_p, [HDC], 'ARB_extensions_string')
PFNWGLGETEXTENSIONSSTRINGARBPROC = CFUNCTYPE(c_char_p, HDC)
WGL_ARB_pixel_format = 1
wglGetPixelFormatAttribivARB = _link_function('wglGetPixelFormatAttribivARB', BOOL, [HDC, c_int, c_int, UINT, POINTER(c_int), POINTER(c_int)], 'ARB_pixel_format')
FLOAT = c_float
wglGetPixelFormatAttribfvARB = _link_function('wglGetPixelFormatAttribfvARB', BOOL, [HDC, c_int, c_int, UINT, POINTER(c_int), POINTER(FLOAT)], 'ARB_pixel_format')
wglChoosePixelFormatARB = _link_function('wglChoosePixelFormatARB', BOOL, [HDC, POINTER(c_int), POINTER(FLOAT), UINT, POINTER(c_int), POINTER(UINT)], 'ARB_pixel_format')
PFNWGLGETPIXELFORMATATTRIBIVARBPROC = CFUNCTYPE(BOOL, HDC, c_int, c_int, UINT, POINTER(c_int), POINTER(c_int))
PFNWGLGETPIXELFORMATATTRIBFVARBPROC = CFUNCTYPE(BOOL, HDC, c_int, c_int, UINT, POINTER(c_int), POINTER(FLOAT))
PFNWGLCHOOSEPIXELFORMATARBPROC = CFUNCTYPE(BOOL, HDC, POINTER(c_int), POINTER(FLOAT), UINT, POINTER(c_int), POINTER(UINT))
WGL_ARB_make_current_read = 1
HGLRC = HANDLE
wglMakeContextCurrentARB = _link_function('wglMakeContextCurrentARB', BOOL, [HDC, HDC, HGLRC], 'ARB_make_current_read')
wglGetCurrentReadDCARB = _link_function('wglGetCurrentReadDCARB', HDC, [], 'ARB_make_current_read')
PFNWGLMAKECONTEXTCURRENTARBPROC = CFUNCTYPE(BOOL, HDC, HDC, HGLRC)
PFNWGLGETCURRENTREADDCARBPROC = CFUNCTYPE(HDC)
WGL_ARB_pbuffer = 1
wglCreatePbufferARB = _link_function('wglCreatePbufferARB', HPBUFFERARB, [HDC, c_int, c_int, c_int, POINTER(c_int)], 'ARB_pbuffer')
wglGetPbufferDCARB = _link_function('wglGetPbufferDCARB', HDC, [HPBUFFERARB], 'ARB_pbuffer')
wglReleasePbufferDCARB = _link_function('wglReleasePbufferDCARB', c_int, [HPBUFFERARB, HDC], 'ARB_pbuffer')
wglDestroyPbufferARB = _link_function('wglDestroyPbufferARB', BOOL, [HPBUFFERARB], 'ARB_pbuffer')
wglQueryPbufferARB = _link_function('wglQueryPbufferARB', BOOL, [HPBUFFERARB, c_int, POINTER(c_int)], 'ARB_pbuffer')
PFNWGLCREATEPBUFFERARBPROC = CFUNCTYPE(HPBUFFERARB, HDC, c_int, c_int, c_int, POINTER(c_int))
PFNWGLGETPBUFFERDCARBPROC = CFUNCTYPE(HDC, HPBUFFERARB)
PFNWGLRELEASEPBUFFERDCARBPROC = CFUNCTYPE(c_int, HPBUFFERARB, HDC)
PFNWGLDESTROYPBUFFERARBPROC = CFUNCTYPE(BOOL, HPBUFFERARB)
PFNWGLQUERYPBUFFERARBPROC = CFUNCTYPE(BOOL, HPBUFFERARB, c_int, POINTER(c_int))
WGL_ARB_render_texture = 1
wglBindTexImageARB = _link_function('wglBindTexImageARB', BOOL, [HPBUFFERARB, c_int], 'ARB_render_texture')
wglReleaseTexImageARB = _link_function('wglReleaseTexImageARB', BOOL, [HPBUFFERARB, c_int], 'ARB_render_texture')
wglSetPbufferAttribARB = _link_function('wglSetPbufferAttribARB', BOOL, [HPBUFFERARB, POINTER(c_int)], 'ARB_render_texture')
PFNWGLBINDTEXIMAGEARBPROC = CFUNCTYPE(BOOL, HPBUFFERARB, c_int)
PFNWGLRELEASETEXIMAGEARBPROC = CFUNCTYPE(BOOL, HPBUFFERARB, c_int)
PFNWGLSETPBUFFERATTRIBARBPROC = CFUNCTYPE(BOOL, HPBUFFERARB, POINTER(c_int))
WGL_ARB_pixel_format_float = 1
WGL_ARB_create_context = 1
wglCreateContextAttribsARB = _link_function('wglCreateContextAttribsARB', HGLRC, [HDC, HGLRC, POINTER(c_int)], 'ARB_create_context')
PFNWGLCREATECONTEXTATTRIBSARBPROC = CFUNCTYPE(HGLRC, HDC, HGLRC, POINTER(c_int))
WGL_EXT_display_color_table = 1
GLboolean = c_ubyte
GLushort = c_ushort
wglCreateDisplayColorTableEXT = _link_function('wglCreateDisplayColorTableEXT', GLboolean, [GLushort], 'EXT_display_color_table')
GLuint = c_uint
wglLoadDisplayColorTableEXT = _link_function('wglLoadDisplayColorTableEXT', GLboolean, [POINTER(GLushort), GLuint], 'EXT_display_color_table')
wglBindDisplayColorTableEXT = _link_function('wglBindDisplayColorTableEXT', GLboolean, [GLushort], 'EXT_display_color_table')
wglDestroyDisplayColorTableEXT = _link_function('wglDestroyDisplayColorTableEXT', VOID, [GLushort], 'EXT_display_color_table')
PFNWGLCREATEDISPLAYCOLORTABLEEXTPROC = CFUNCTYPE(GLboolean, GLushort)
PFNWGLLOADDISPLAYCOLORTABLEEXTPROC = CFUNCTYPE(GLboolean, POINTER(GLushort), GLuint)
PFNWGLBINDDISPLAYCOLORTABLEEXTPROC = CFUNCTYPE(GLboolean, GLushort)
PFNWGLDESTROYDISPLAYCOLORTABLEEXTPROC = CFUNCTYPE(VOID, GLushort)
WGL_EXT_extensions_string = 1
wglGetExtensionsStringEXT = _link_function('wglGetExtensionsStringEXT', c_char_p, [], 'EXT_extensions_string')
PFNWGLGETEXTENSIONSSTRINGEXTPROC = CFUNCTYPE(c_char_p)
WGL_EXT_make_current_read = 1
wglMakeContextCurrentEXT = _link_function('wglMakeContextCurrentEXT', BOOL, [HDC, HDC, HGLRC], 'EXT_make_current_read')
wglGetCurrentReadDCEXT = _link_function('wglGetCurrentReadDCEXT', HDC, [], 'EXT_make_current_read')
PFNWGLMAKECONTEXTCURRENTEXTPROC = CFUNCTYPE(BOOL, HDC, HDC, HGLRC)
PFNWGLGETCURRENTREADDCEXTPROC = CFUNCTYPE(HDC)
WGL_EXT_pbuffer = 1
wglCreatePbufferEXT = _link_function('wglCreatePbufferEXT', HPBUFFEREXT, [HDC, c_int, c_int, c_int, POINTER(c_int)], 'EXT_pbuffer')
wglGetPbufferDCEXT = _link_function('wglGetPbufferDCEXT', HDC, [HPBUFFEREXT], 'EXT_pbuffer')
wglReleasePbufferDCEXT = _link_function('wglReleasePbufferDCEXT', c_int, [HPBUFFEREXT, HDC], 'EXT_pbuffer')
wglDestroyPbufferEXT = _link_function('wglDestroyPbufferEXT', BOOL, [HPBUFFEREXT], 'EXT_pbuffer')
wglQueryPbufferEXT = _link_function('wglQueryPbufferEXT', BOOL, [HPBUFFEREXT, c_int, POINTER(c_int)], 'EXT_pbuffer')
PFNWGLCREATEPBUFFEREXTPROC = CFUNCTYPE(HPBUFFEREXT, HDC, c_int, c_int, c_int, POINTER(c_int))
PFNWGLGETPBUFFERDCEXTPROC = CFUNCTYPE(HDC, HPBUFFEREXT)
PFNWGLRELEASEPBUFFERDCEXTPROC = CFUNCTYPE(c_int, HPBUFFEREXT, HDC)
PFNWGLDESTROYPBUFFEREXTPROC = CFUNCTYPE(BOOL, HPBUFFEREXT)
PFNWGLQUERYPBUFFEREXTPROC = CFUNCTYPE(BOOL, HPBUFFEREXT, c_int, POINTER(c_int))
WGL_EXT_pixel_format = 1
wglGetPixelFormatAttribivEXT = _link_function('wglGetPixelFormatAttribivEXT', BOOL, [HDC, c_int, c_int, UINT, POINTER(c_int), POINTER(c_int)], 'EXT_pixel_format')
wglGetPixelFormatAttribfvEXT = _link_function('wglGetPixelFormatAttribfvEXT', BOOL, [HDC, c_int, c_int, UINT, POINTER(c_int), POINTER(FLOAT)], 'EXT_pixel_format')
wglChoosePixelFormatEXT = _link_function('wglChoosePixelFormatEXT', BOOL, [HDC, POINTER(c_int), POINTER(FLOAT), UINT, POINTER(c_int), POINTER(UINT)], 'EXT_pixel_format')
PFNWGLGETPIXELFORMATATTRIBIVEXTPROC = CFUNCTYPE(BOOL, HDC, c_int, c_int, UINT, POINTER(c_int), POINTER(c_int))
PFNWGLGETPIXELFORMATATTRIBFVEXTPROC = CFUNCTYPE(BOOL, HDC, c_int, c_int, UINT, POINTER(c_int), POINTER(FLOAT))
PFNWGLCHOOSEPIXELFORMATEXTPROC = CFUNCTYPE(BOOL, HDC, POINTER(c_int), POINTER(FLOAT), UINT, POINTER(c_int), POINTER(UINT))
WGL_EXT_swap_control = 1
wglSwapIntervalEXT = _link_function('wglSwapIntervalEXT', BOOL, [c_int], 'EXT_swap_control')
wglGetSwapIntervalEXT = _link_function('wglGetSwapIntervalEXT', c_int, [], 'EXT_swap_control')
PFNWGLSWAPINTERVALEXTPROC = CFUNCTYPE(BOOL, c_int)
PFNWGLGETSWAPINTERVALEXTPROC = CFUNCTYPE(c_int)
WGL_EXT_depth_float = 1
WGL_NV_vertex_array_range = 1
GLsizei = c_int
GLfloat = c_float
wglAllocateMemoryNV = _link_function('wglAllocateMemoryNV', POINTER(c_void), [GLsizei, GLfloat, GLfloat, GLfloat], 'NV_vertex_array_range')
wglFreeMemoryNV = _link_function('wglFreeMemoryNV', None, [POINTER(None)], 'NV_vertex_array_range')
PFNWGLALLOCATEMEMORYNVPROC = CFUNCTYPE(POINTER(c_void), GLsizei, GLfloat, GLfloat, GLfloat)
PFNWGLFREEMEMORYNVPROC = CFUNCTYPE(None, POINTER(None))
WGL_3DFX_multisample = 1
WGL_EXT_multisample = 1
WGL_OML_sync_control = 1
INT64 = c_longlong
wglGetSyncValuesOML = _link_function('wglGetSyncValuesOML', BOOL, [HDC, POINTER(INT64), POINTER(INT64), POINTER(INT64)], 'OML_sync_control')
INT32 = c_int
wglGetMscRateOML = _link_function('wglGetMscRateOML', BOOL, [HDC, POINTER(INT32), POINTER(INT32)], 'OML_sync_control')
wglSwapBuffersMscOML = _link_function('wglSwapBuffersMscOML', INT64, [HDC, INT64, INT64, INT64], 'OML_sync_control')
wglSwapLayerBuffersMscOML = _link_function('wglSwapLayerBuffersMscOML', INT64, [HDC, c_int, INT64, INT64, INT64], 'OML_sync_control')
wglWaitForMscOML = _link_function('wglWaitForMscOML', BOOL, [HDC, INT64, INT64, INT64, POINTER(INT64), POINTER(INT64), POINTER(INT64)], 'OML_sync_control')
wglWaitForSbcOML = _link_function('wglWaitForSbcOML', BOOL, [HDC, INT64, POINTER(INT64), POINTER(INT64), POINTER(INT64)], 'OML_sync_control')
PFNWGLGETSYNCVALUESOMLPROC = CFUNCTYPE(BOOL, HDC, POINTER(INT64), POINTER(INT64), POINTER(INT64))
PFNWGLGETMSCRATEOMLPROC = CFUNCTYPE(BOOL, HDC, POINTER(INT32), POINTER(INT32))
PFNWGLSWAPBUFFERSMSCOMLPROC = CFUNCTYPE(INT64, HDC, INT64, INT64, INT64)
PFNWGLSWAPLAYERBUFFERSMSCOMLPROC = CFUNCTYPE(INT64, HDC, c_int, INT64, INT64, INT64)
PFNWGLWAITFORMSCOMLPROC = CFUNCTYPE(BOOL, HDC, INT64, INT64, INT64, POINTER(INT64), POINTER(INT64), POINTER(INT64))
PFNWGLWAITFORSBCOMLPROC = CFUNCTYPE(BOOL, HDC, INT64, POINTER(INT64), POINTER(INT64), POINTER(INT64))
WGL_I3D_digital_video_control = 1
wglGetDigitalVideoParametersI3D = _link_function('wglGetDigitalVideoParametersI3D', BOOL, [HDC, c_int, POINTER(c_int)], 'I3D_digital_video_control')
wglSetDigitalVideoParametersI3D = _link_function('wglSetDigitalVideoParametersI3D', BOOL, [HDC, c_int, POINTER(c_int)], 'I3D_digital_video_control')
PFNWGLGETDIGITALVIDEOPARAMETERSI3DPROC = CFUNCTYPE(BOOL, HDC, c_int, POINTER(c_int))
PFNWGLSETDIGITALVIDEOPARAMETERSI3DPROC = CFUNCTYPE(BOOL, HDC, c_int, POINTER(c_int))
WGL_I3D_gamma = 1
wglGetGammaTableParametersI3D = _link_function('wglGetGammaTableParametersI3D', BOOL, [HDC, c_int, POINTER(c_int)], 'I3D_gamma')
wglSetGammaTableParametersI3D = _link_function('wglSetGammaTableParametersI3D', BOOL, [HDC, c_int, POINTER(c_int)], 'I3D_gamma')
USHORT = c_ushort
wglGetGammaTableI3D = _link_function('wglGetGammaTableI3D', BOOL, [HDC, c_int, POINTER(USHORT), POINTER(USHORT), POINTER(USHORT)], 'I3D_gamma')
wglSetGammaTableI3D = _link_function('wglSetGammaTableI3D', BOOL, [HDC, c_int, POINTER(USHORT), POINTER(USHORT), POINTER(USHORT)], 'I3D_gamma')
PFNWGLGETGAMMATABLEPARAMETERSI3DPROC = CFUNCTYPE(BOOL, HDC, c_int, POINTER(c_int))
PFNWGLSETGAMMATABLEPARAMETERSI3DPROC = CFUNCTYPE(BOOL, HDC, c_int, POINTER(c_int))
PFNWGLGETGAMMATABLEI3DPROC = CFUNCTYPE(BOOL, HDC, c_int, POINTER(USHORT), POINTER(USHORT), POINTER(USHORT))
PFNWGLSETGAMMATABLEI3DPROC = CFUNCTYPE(BOOL, HDC, c_int, POINTER(USHORT), POINTER(USHORT), POINTER(USHORT))
WGL_I3D_genlock = 1
wglEnableGenlockI3D = _link_function('wglEnableGenlockI3D', BOOL, [HDC], 'I3D_genlock')
wglDisableGenlockI3D = _link_function('wglDisableGenlockI3D', BOOL, [HDC], 'I3D_genlock')
wglIsEnabledGenlockI3D = _link_function('wglIsEnabledGenlockI3D', BOOL, [HDC, POINTER(BOOL)], 'I3D_genlock')
wglGenlockSourceI3D = _link_function('wglGenlockSourceI3D', BOOL, [HDC, UINT], 'I3D_genlock')
wglGetGenlockSourceI3D = _link_function('wglGetGenlockSourceI3D', BOOL, [HDC, POINTER(UINT)], 'I3D_genlock')
wglGenlockSourceEdgeI3D = _link_function('wglGenlockSourceEdgeI3D', BOOL, [HDC, UINT], 'I3D_genlock')
wglGetGenlockSourceEdgeI3D = _link_function('wglGetGenlockSourceEdgeI3D', BOOL, [HDC, POINTER(UINT)], 'I3D_genlock')
wglGenlockSampleRateI3D = _link_function('wglGenlockSampleRateI3D', BOOL, [HDC, UINT], 'I3D_genlock')
wglGetGenlockSampleRateI3D = _link_function('wglGetGenlockSampleRateI3D', BOOL, [HDC, POINTER(UINT)], 'I3D_genlock')
wglGenlockSourceDelayI3D = _link_function('wglGenlockSourceDelayI3D', BOOL, [HDC, UINT], 'I3D_genlock')
wglGetGenlockSourceDelayI3D = _link_function('wglGetGenlockSourceDelayI3D', BOOL, [HDC, POINTER(UINT)], 'I3D_genlock')
wglQueryGenlockMaxSourceDelayI3D = _link_function('wglQueryGenlockMaxSourceDelayI3D', BOOL, [HDC, POINTER(UINT), POINTER(UINT)], 'I3D_genlock')
PFNWGLENABLEGENLOCKI3DPROC = CFUNCTYPE(BOOL, HDC)
PFNWGLDISABLEGENLOCKI3DPROC = CFUNCTYPE(BOOL, HDC)
PFNWGLISENABLEDGENLOCKI3DPROC = CFUNCTYPE(BOOL, HDC, POINTER(BOOL))
PFNWGLGENLOCKSOURCEI3DPROC = CFUNCTYPE(BOOL, HDC, UINT)
PFNWGLGETGENLOCKSOURCEI3DPROC = CFUNCTYPE(BOOL, HDC, POINTER(UINT))
PFNWGLGENLOCKSOURCEEDGEI3DPROC = CFUNCTYPE(BOOL, HDC, UINT)
PFNWGLGETGENLOCKSOURCEEDGEI3DPROC = CFUNCTYPE(BOOL, HDC, POINTER(UINT))
PFNWGLGENLOCKSAMPLERATEI3DPROC = CFUNCTYPE(BOOL, HDC, UINT)
PFNWGLGETGENLOCKSAMPLERATEI3DPROC = CFUNCTYPE(BOOL, HDC, POINTER(UINT))
PFNWGLGENLOCKSOURCEDELAYI3DPROC = CFUNCTYPE(BOOL, HDC, UINT)
PFNWGLGETGENLOCKSOURCEDELAYI3DPROC = CFUNCTYPE(BOOL, HDC, POINTER(UINT))
PFNWGLQUERYGENLOCKMAXSOURCEDELAYI3DPROC = CFUNCTYPE(BOOL, HDC, POINTER(UINT), POINTER(UINT))
WGL_I3D_image_buffer = 1
LPVOID = POINTER(None)
wglCreateImageBufferI3D = _link_function('wglCreateImageBufferI3D', LPVOID, [HDC, DWORD, UINT], 'I3D_image_buffer')
wglDestroyImageBufferI3D = _link_function('wglDestroyImageBufferI3D', BOOL, [HDC, LPVOID], 'I3D_image_buffer')
wglAssociateImageBufferEventsI3D = _link_function('wglAssociateImageBufferEventsI3D', BOOL, [HDC, POINTER(HANDLE), POINTER(LPVOID), POINTER(DWORD), UINT], 'I3D_image_buffer')
wglReleaseImageBufferEventsI3D = _link_function('wglReleaseImageBufferEventsI3D', BOOL, [HDC, POINTER(LPVOID), UINT], 'I3D_image_buffer')
PFNWGLCREATEIMAGEBUFFERI3DPROC = CFUNCTYPE(LPVOID, HDC, DWORD, UINT)
PFNWGLDESTROYIMAGEBUFFERI3DPROC = CFUNCTYPE(BOOL, HDC, LPVOID)
PFNWGLASSOCIATEIMAGEBUFFEREVENTSI3DPROC = CFUNCTYPE(BOOL, HDC, POINTER(HANDLE), POINTER(LPVOID), POINTER(DWORD), UINT)
PFNWGLRELEASEIMAGEBUFFEREVENTSI3DPROC = CFUNCTYPE(BOOL, HDC, POINTER(LPVOID), UINT)
WGL_I3D_swap_frame_lock = 1
wglEnableFrameLockI3D = _link_function('wglEnableFrameLockI3D', BOOL, [], 'I3D_swap_frame_lock')
wglDisableFrameLockI3D = _link_function('wglDisableFrameLockI3D', BOOL, [], 'I3D_swap_frame_lock')
wglIsEnabledFrameLockI3D = _link_function('wglIsEnabledFrameLockI3D', BOOL, [POINTER(BOOL)], 'I3D_swap_frame_lock')
wglQueryFrameLockMasterI3D = _link_function('wglQueryFrameLockMasterI3D', BOOL, [POINTER(BOOL)], 'I3D_swap_frame_lock')
PFNWGLENABLEFRAMELOCKI3DPROC = CFUNCTYPE(BOOL)
PFNWGLDISABLEFRAMELOCKI3DPROC = CFUNCTYPE(BOOL)
PFNWGLISENABLEDFRAMELOCKI3DPROC = CFUNCTYPE(BOOL, POINTER(BOOL))
PFNWGLQUERYFRAMELOCKMASTERI3DPROC = CFUNCTYPE(BOOL, POINTER(BOOL))
WGL_I3D_swap_frame_usage = 1
wglGetFrameUsageI3D = _link_function('wglGetFrameUsageI3D', BOOL, [POINTER(c_float)], 'I3D_swap_frame_usage')
wglBeginFrameTrackingI3D = _link_function('wglBeginFrameTrackingI3D', BOOL, [], 'I3D_swap_frame_usage')
wglEndFrameTrackingI3D = _link_function('wglEndFrameTrackingI3D', BOOL, [], 'I3D_swap_frame_usage')
wglQueryFrameTrackingI3D = _link_function('wglQueryFrameTrackingI3D', BOOL, [POINTER(DWORD), POINTER(DWORD), POINTER(c_float)], 'I3D_swap_frame_usage')
PFNWGLGETFRAMEUSAGEI3DPROC = CFUNCTYPE(BOOL, POINTER(c_float))
PFNWGLBEGINFRAMETRACKINGI3DPROC = CFUNCTYPE(BOOL)
PFNWGLENDFRAMETRACKINGI3DPROC = CFUNCTYPE(BOOL)
PFNWGLQUERYFRAMETRACKINGI3DPROC = CFUNCTYPE(BOOL, POINTER(DWORD), POINTER(DWORD), POINTER(c_float))
WGL_ATI_pixel_format_float = 1
WGL_NV_float_buffer = 1
WGL_EXT_pixel_format_packed_float = 1
WGL_EXT_framebuffer_sRGB = 1
WGL_NV_present_video = 1
wglEnumerateVideoDevicesNV = _link_function('wglEnumerateVideoDevicesNV', c_int, [HDC, POINTER(HVIDEOOUTPUTDEVICENV)], 'NV_present_video')
wglBindVideoDeviceNV = _link_function('wglBindVideoDeviceNV', BOOL, [HDC, c_uint, HVIDEOOUTPUTDEVICENV, POINTER(c_int)], 'NV_present_video')
wglQueryCurrentContextNV = _link_function('wglQueryCurrentContextNV', BOOL, [c_int, POINTER(c_int)], 'NV_present_video')
PFNWGLENUMERATEVIDEODEVICESNVPROC = CFUNCTYPE(c_int, HDC, POINTER(HVIDEOOUTPUTDEVICENV))
PFNWGLBINDVIDEODEVICENVPROC = CFUNCTYPE(BOOL, HDC, c_uint, HVIDEOOUTPUTDEVICENV, POINTER(c_int))
PFNWGLQUERYCURRENTCONTEXTNVPROC = CFUNCTYPE(BOOL, c_int, POINTER(c_int))
WGL_NV_video_out = 1
wglGetVideoDeviceNV = _link_function('wglGetVideoDeviceNV', BOOL, [HDC, c_int, POINTER(HPVIDEODEV)], 'NV_video_out')
wglReleaseVideoDeviceNV = _link_function('wglReleaseVideoDeviceNV', BOOL, [HPVIDEODEV], 'NV_video_out')
wglBindVideoImageNV = _link_function('wglBindVideoImageNV', BOOL, [HPVIDEODEV, HPBUFFERARB, c_int], 'NV_video_out')
wglReleaseVideoImageNV = _link_function('wglReleaseVideoImageNV', BOOL, [HPBUFFERARB, c_int], 'NV_video_out')
wglSendPbufferToVideoNV = _link_function('wglSendPbufferToVideoNV', BOOL, [HPBUFFERARB, c_int, POINTER(c_ulong), BOOL], 'NV_video_out')
wglGetVideoInfoNV = _link_function('wglGetVideoInfoNV', BOOL, [HPVIDEODEV, POINTER(c_ulong), POINTER(c_ulong)], 'NV_video_out')
PFNWGLGETVIDEODEVICENVPROC = CFUNCTYPE(BOOL, HDC, c_int, POINTER(HPVIDEODEV))
PFNWGLRELEASEVIDEODEVICENVPROC = CFUNCTYPE(BOOL, HPVIDEODEV)
PFNWGLBINDVIDEOIMAGENVPROC = CFUNCTYPE(BOOL, HPVIDEODEV, HPBUFFERARB, c_int)
PFNWGLRELEASEVIDEOIMAGENVPROC = CFUNCTYPE(BOOL, HPBUFFERARB, c_int)
PFNWGLSENDPBUFFERTOVIDEONVPROC = CFUNCTYPE(BOOL, HPBUFFERARB, c_int, POINTER(c_ulong), BOOL)
PFNWGLGETVIDEOINFONVPROC = CFUNCTYPE(BOOL, HPVIDEODEV, POINTER(c_ulong), POINTER(c_ulong))
WGL_NV_swap_group = 1
wglJoinSwapGroupNV = _link_function('wglJoinSwapGroupNV', BOOL, [HDC, GLuint], 'NV_swap_group')
wglBindSwapBarrierNV = _link_function('wglBindSwapBarrierNV', BOOL, [GLuint, GLuint], 'NV_swap_group')
wglQuerySwapGroupNV = _link_function('wglQuerySwapGroupNV', BOOL, [HDC, POINTER(GLuint), POINTER(GLuint)], 'NV_swap_group')
wglQueryMaxSwapGroupsNV = _link_function('wglQueryMaxSwapGroupsNV', BOOL, [HDC, POINTER(GLuint), POINTER(GLuint)], 'NV_swap_group')
wglQueryFrameCountNV = _link_function('wglQueryFrameCountNV', BOOL, [HDC, POINTER(GLuint)], 'NV_swap_group')
wglResetFrameCountNV = _link_function('wglResetFrameCountNV', BOOL, [HDC], 'NV_swap_group')
PFNWGLJOINSWAPGROUPNVPROC = CFUNCTYPE(BOOL, HDC, GLuint)
PFNWGLBINDSWAPBARRIERNVPROC = CFUNCTYPE(BOOL, GLuint, GLuint)
PFNWGLQUERYSWAPGROUPNVPROC = CFUNCTYPE(BOOL, HDC, POINTER(GLuint), POINTER(GLuint))
PFNWGLQUERYMAXSWAPGROUPSNVPROC = CFUNCTYPE(BOOL, HDC, POINTER(GLuint), POINTER(GLuint))
PFNWGLQUERYFRAMECOUNTNVPROC = CFUNCTYPE(BOOL, HDC, POINTER(GLuint))
PFNWGLRESETFRAMECOUNTNVPROC = CFUNCTYPE(BOOL, HDC)
WGL_NV_gpu_affinity = 1
wglEnumGpusNV = _link_function('wglEnumGpusNV', BOOL, [UINT, POINTER(HGPUNV)], 'NV_gpu_affinity')
wglEnumGpuDevicesNV = _link_function('wglEnumGpuDevicesNV', BOOL, [HGPUNV, UINT, PGPU_DEVICE], 'NV_gpu_affinity')
wglCreateAffinityDCNV = _link_function('wglCreateAffinityDCNV', HDC, [POINTER(HGPUNV)], 'NV_gpu_affinity')
wglEnumGpusFromAffinityDCNV = _link_function('wglEnumGpusFromAffinityDCNV', BOOL, [HDC, UINT, POINTER(HGPUNV)], 'NV_gpu_affinity')
wglDeleteDCNV = _link_function('wglDeleteDCNV', BOOL, [HDC], 'NV_gpu_affinity')
PFNWGLENUMGPUSNVPROC = CFUNCTYPE(BOOL, UINT, POINTER(HGPUNV))
PFNWGLENUMGPUDEVICESNVPROC = CFUNCTYPE(BOOL, HGPUNV, UINT, PGPU_DEVICE)
PFNWGLCREATEAFFINITYDCNVPROC = CFUNCTYPE(HDC, POINTER(HGPUNV))
PFNWGLENUMGPUSFROMAFFINITYDCNVPROC = CFUNCTYPE(BOOL, HDC, UINT, POINTER(HGPUNV))
PFNWGLDELETEDCNVPROC = CFUNCTYPE(BOOL, HDC)
__all__ = [
 'WIN32_LEAN_AND_MEAN', 'WGL_WGLEXT_VERSION', 
 'WGL_FRONT_COLOR_BUFFER_BIT_ARB', 
 'WGL_BACK_COLOR_BUFFER_BIT_ARB', 
 'WGL_DEPTH_BUFFER_BIT_ARB', 'WGL_STENCIL_BUFFER_BIT_ARB', 
 'WGL_SAMPLE_BUFFERS_ARB', 
 'WGL_SAMPLES_ARB', 'WGL_NUMBER_PIXEL_FORMATS_ARB', 
 'WGL_DRAW_TO_WINDOW_ARB', 
 'WGL_DRAW_TO_BITMAP_ARB', 'WGL_ACCELERATION_ARB', 
 'WGL_NEED_PALETTE_ARB', 
 'WGL_NEED_SYSTEM_PALETTE_ARB', 
 'WGL_SWAP_LAYER_BUFFERS_ARB', 'WGL_SWAP_METHOD_ARB', 
 'WGL_NUMBER_OVERLAYS_ARB', 
 'WGL_NUMBER_UNDERLAYS_ARB', 'WGL_TRANSPARENT_ARB', 
 'WGL_TRANSPARENT_RED_VALUE_ARB', 
 'WGL_TRANSPARENT_GREEN_VALUE_ARB', 
 'WGL_TRANSPARENT_BLUE_VALUE_ARB', 'WGL_TRANSPARENT_ALPHA_VALUE_ARB', 
 'WGL_TRANSPARENT_INDEX_VALUE_ARB', 
 'WGL_SHARE_DEPTH_ARB', 
 'WGL_SHARE_STENCIL_ARB', 'WGL_SHARE_ACCUM_ARB', 'WGL_SUPPORT_GDI_ARB', 
 'WGL_SUPPORT_OPENGL_ARB', 
 'WGL_DOUBLE_BUFFER_ARB', 'WGL_STEREO_ARB', 
 'WGL_PIXEL_TYPE_ARB', 'WGL_COLOR_BITS_ARB', 
 'WGL_RED_BITS_ARB', 
 'WGL_RED_SHIFT_ARB', 'WGL_GREEN_BITS_ARB', 'WGL_GREEN_SHIFT_ARB', 
 'WGL_BLUE_BITS_ARB', 
 'WGL_BLUE_SHIFT_ARB', 'WGL_ALPHA_BITS_ARB', 
 'WGL_ALPHA_SHIFT_ARB', 'WGL_ACCUM_BITS_ARB', 
 'WGL_ACCUM_RED_BITS_ARB', 
 'WGL_ACCUM_GREEN_BITS_ARB', 'WGL_ACCUM_BLUE_BITS_ARB', 
 'WGL_ACCUM_ALPHA_BITS_ARB', 
 'WGL_DEPTH_BITS_ARB', 'WGL_STENCIL_BITS_ARB', 
 'WGL_AUX_BUFFERS_ARB', 'WGL_NO_ACCELERATION_ARB', 
 'WGL_GENERIC_ACCELERATION_ARB', 
 'WGL_FULL_ACCELERATION_ARB', 
 'WGL_SWAP_EXCHANGE_ARB', 'WGL_SWAP_COPY_ARB', 
 'WGL_SWAP_UNDEFINED_ARB', 
 'WGL_TYPE_RGBA_ARB', 'WGL_TYPE_COLORINDEX_ARB', 
 'ERROR_INVALID_PIXEL_TYPE_ARB', 
 'ERROR_INCOMPATIBLE_DEVICE_CONTEXTS_ARB', 
 'WGL_DRAW_TO_PBUFFER_ARB', 'WGL_MAX_PBUFFER_PIXELS_ARB', 
 'WGL_MAX_PBUFFER_WIDTH_ARB', 
 'WGL_MAX_PBUFFER_HEIGHT_ARB', 
 'WGL_PBUFFER_LARGEST_ARB', 'WGL_PBUFFER_WIDTH_ARB', 
 'WGL_PBUFFER_HEIGHT_ARB', 
 'WGL_PBUFFER_LOST_ARB', 'WGL_BIND_TO_TEXTURE_RGB_ARB', 
 'WGL_BIND_TO_TEXTURE_RGBA_ARB', 
 'WGL_TEXTURE_FORMAT_ARB', 
 'WGL_TEXTURE_TARGET_ARB', 'WGL_MIPMAP_TEXTURE_ARB', 
 'WGL_TEXTURE_RGB_ARB', 
 'WGL_TEXTURE_RGBA_ARB', 'WGL_NO_TEXTURE_ARB', 'WGL_TEXTURE_CUBE_MAP_ARB', 
 'WGL_TEXTURE_1D_ARB', 
 'WGL_TEXTURE_2D_ARB', 'WGL_MIPMAP_LEVEL_ARB', 
 'WGL_CUBE_MAP_FACE_ARB', 'WGL_TEXTURE_CUBE_MAP_POSITIVE_X_ARB', 
 'WGL_TEXTURE_CUBE_MAP_NEGATIVE_X_ARB', 
 'WGL_TEXTURE_CUBE_MAP_POSITIVE_Y_ARB', 
 'WGL_TEXTURE_CUBE_MAP_NEGATIVE_Y_ARB', 
 'WGL_TEXTURE_CUBE_MAP_POSITIVE_Z_ARB', 
 'WGL_TEXTURE_CUBE_MAP_NEGATIVE_Z_ARB', 
 'WGL_FRONT_LEFT_ARB', 
 'WGL_FRONT_RIGHT_ARB', 'WGL_BACK_LEFT_ARB', 'WGL_BACK_RIGHT_ARB', 
 'WGL_AUX0_ARB', 
 'WGL_AUX1_ARB', 'WGL_AUX2_ARB', 'WGL_AUX3_ARB', 
 'WGL_AUX4_ARB', 'WGL_AUX5_ARB', 
 'WGL_AUX6_ARB', 'WGL_AUX7_ARB', 
 'WGL_AUX8_ARB', 'WGL_AUX9_ARB', 'WGL_TYPE_RGBA_FLOAT_ARB', 
 'WGL_CONTEXT_DEBUG_BIT_ARB', 
 'WGL_CONTEXT_FORWARD_COMPATIBLE_BIT_ARB', 
 'WGL_CONTEXT_MAJOR_VERSION_ARB', 
 'WGL_CONTEXT_MINOR_VERSION_ARB', 
 'WGL_CONTEXT_LAYER_PLANE_ARB', 'WGL_CONTEXT_FLAGS_ARB', 
 'ERROR_INVALID_VERSION_ARB', 
 'ERROR_INVALID_PIXEL_TYPE_EXT', 
 'WGL_NUMBER_PIXEL_FORMATS_EXT', 'WGL_DRAW_TO_WINDOW_EXT', 
 'WGL_DRAW_TO_BITMAP_EXT', 
 'WGL_ACCELERATION_EXT', 'WGL_NEED_PALETTE_EXT', 
 'WGL_NEED_SYSTEM_PALETTE_EXT', 
 'WGL_SWAP_LAYER_BUFFERS_EXT', 
 'WGL_SWAP_METHOD_EXT', 'WGL_NUMBER_OVERLAYS_EXT', 
 'WGL_NUMBER_UNDERLAYS_EXT', 
 'WGL_TRANSPARENT_EXT', 'WGL_TRANSPARENT_VALUE_EXT', 
 'WGL_SHARE_DEPTH_EXT', 
 'WGL_SHARE_STENCIL_EXT', 'WGL_SHARE_ACCUM_EXT', 'WGL_SUPPORT_GDI_EXT', 
 'WGL_SUPPORT_OPENGL_EXT', 
 'WGL_DOUBLE_BUFFER_EXT', 'WGL_STEREO_EXT', 
 'WGL_PIXEL_TYPE_EXT', 'WGL_COLOR_BITS_EXT', 
 'WGL_RED_BITS_EXT', 
 'WGL_RED_SHIFT_EXT', 'WGL_GREEN_BITS_EXT', 'WGL_GREEN_SHIFT_EXT', 
 'WGL_BLUE_BITS_EXT', 
 'WGL_BLUE_SHIFT_EXT', 'WGL_ALPHA_BITS_EXT', 
 'WGL_ALPHA_SHIFT_EXT', 'WGL_ACCUM_BITS_EXT', 
 'WGL_ACCUM_RED_BITS_EXT', 
 'WGL_ACCUM_GREEN_BITS_EXT', 'WGL_ACCUM_BLUE_BITS_EXT', 
 'WGL_ACCUM_ALPHA_BITS_EXT', 
 'WGL_DEPTH_BITS_EXT', 'WGL_STENCIL_BITS_EXT', 
 'WGL_AUX_BUFFERS_EXT', 'WGL_NO_ACCELERATION_EXT', 
 'WGL_GENERIC_ACCELERATION_EXT', 
 'WGL_FULL_ACCELERATION_EXT', 
 'WGL_SWAP_EXCHANGE_EXT', 'WGL_SWAP_COPY_EXT', 
 'WGL_SWAP_UNDEFINED_EXT', 
 'WGL_TYPE_RGBA_EXT', 'WGL_TYPE_COLORINDEX_EXT', 
 'WGL_DRAW_TO_PBUFFER_EXT', 
 'WGL_MAX_PBUFFER_PIXELS_EXT', 'WGL_MAX_PBUFFER_WIDTH_EXT', 
 'WGL_MAX_PBUFFER_HEIGHT_EXT', 
 'WGL_OPTIMAL_PBUFFER_WIDTH_EXT', 
 'WGL_OPTIMAL_PBUFFER_HEIGHT_EXT', 'WGL_PBUFFER_LARGEST_EXT', 
 'WGL_PBUFFER_WIDTH_EXT', 
 'WGL_PBUFFER_HEIGHT_EXT', 'WGL_DEPTH_FLOAT_EXT', 
 'WGL_SAMPLE_BUFFERS_3DFX', 
 'WGL_SAMPLES_3DFX', 'WGL_SAMPLE_BUFFERS_EXT', 
 'WGL_SAMPLES_EXT', 'WGL_DIGITAL_VIDEO_CURSOR_ALPHA_FRAMEBUFFER_I3D', 
 'WGL_DIGITAL_VIDEO_CURSOR_ALPHA_VALUE_I3D', 
 'WGL_DIGITAL_VIDEO_CURSOR_INCLUDED_I3D', 
 'WGL_DIGITAL_VIDEO_GAMMA_CORRECTED_I3D', 
 'WGL_GAMMA_TABLE_SIZE_I3D', 
 'WGL_GAMMA_EXCLUDE_DESKTOP_I3D', 'WGL_GENLOCK_SOURCE_MULTIVIEW_I3D', 
 'WGL_GENLOCK_SOURCE_EXTENAL_SYNC_I3D', 
 'WGL_GENLOCK_SOURCE_EXTENAL_FIELD_I3D', 
 'WGL_GENLOCK_SOURCE_EXTENAL_TTL_I3D', 
 'WGL_GENLOCK_SOURCE_DIGITAL_SYNC_I3D', 
 'WGL_GENLOCK_SOURCE_DIGITAL_FIELD_I3D', 
 'WGL_GENLOCK_SOURCE_EDGE_FALLING_I3D', 
 'WGL_GENLOCK_SOURCE_EDGE_RISING_I3D', 
 'WGL_GENLOCK_SOURCE_EDGE_BOTH_I3D', 
 'WGL_IMAGE_BUFFER_MIN_ACCESS_I3D', 'WGL_IMAGE_BUFFER_LOCK_I3D', 
 'WGL_BIND_TO_TEXTURE_DEPTH_NV', 
 'WGL_BIND_TO_TEXTURE_RECTANGLE_DEPTH_NV', 
 'WGL_DEPTH_TEXTURE_FORMAT_NV', 
 'WGL_TEXTURE_DEPTH_COMPONENT_NV', 
 'WGL_DEPTH_COMPONENT_NV', 'WGL_BIND_TO_TEXTURE_RECTANGLE_RGB_NV', 
 'WGL_BIND_TO_TEXTURE_RECTANGLE_RGBA_NV', 
 'WGL_TEXTURE_RECTANGLE_NV', 
 'WGL_TYPE_RGBA_FLOAT_ATI', 'WGL_FLOAT_COMPONENTS_NV', 
 'WGL_BIND_TO_TEXTURE_RECTANGLE_FLOAT_R_NV', 
 'WGL_BIND_TO_TEXTURE_RECTANGLE_FLOAT_RG_NV', 
 'WGL_BIND_TO_TEXTURE_RECTANGLE_FLOAT_RGB_NV', 
 'WGL_BIND_TO_TEXTURE_RECTANGLE_FLOAT_RGBA_NV', 
 'WGL_TEXTURE_FLOAT_R_NV', 
 'WGL_TEXTURE_FLOAT_RG_NV', 'WGL_TEXTURE_FLOAT_RGB_NV', 
 'WGL_TEXTURE_FLOAT_RGBA_NV', 
 'WGL_STEREO_EMITTER_ENABLE_3DL', 
 'WGL_STEREO_EMITTER_DISABLE_3DL', 'WGL_STEREO_POLARITY_NORMAL_3DL', 
 'WGL_STEREO_POLARITY_INVERT_3DL', 
 'WGL_TYPE_RGBA_UNSIGNED_FLOAT_EXT', 
 'WGL_FRAMEBUFFER_SRGB_CAPABLE_EXT', 'WGL_NUM_VIDEO_SLOTS_NV', 
 'WGL_BIND_TO_VIDEO_RGB_NV', 
 'WGL_BIND_TO_VIDEO_RGBA_NV', 
 'WGL_BIND_TO_VIDEO_RGB_AND_DEPTH_NV', 'WGL_VIDEO_OUT_COLOR_NV', 
 'WGL_VIDEO_OUT_ALPHA_NV', 
 'WGL_VIDEO_OUT_DEPTH_NV', 
 'WGL_VIDEO_OUT_COLOR_AND_ALPHA_NV', 'WGL_VIDEO_OUT_COLOR_AND_DEPTH_NV', 
 'WGL_VIDEO_OUT_FRAME', 
 'WGL_VIDEO_OUT_FIELD_1', 'WGL_VIDEO_OUT_FIELD_2', 
 'WGL_VIDEO_OUT_STACKED_FIELDS_1_2', 
 'WGL_VIDEO_OUT_STACKED_FIELDS_2_1', 
 'WGL_ERROR_INCOMPATIBLE_AFFINITY_MASKS_NV', 
 'WGL_ERROR_MISSING_AFFINITY_MASK_NV', 
 'HPBUFFERARB', 'HPBUFFEREXT', 
 'HVIDEOOUTPUTDEVICENV', 'HPVIDEODEV', 'HPGPUNV', 
 'HGPUNV', 'GPU_DEVICE', 
 'PGPU_DEVICE', 'WGL_ARB_buffer_region', 'wglCreateBufferRegionARB', 
 'wglDeleteBufferRegionARB', 
 'wglSaveBufferRegionARB', 
 'wglRestoreBufferRegionARB', 'PFNWGLCREATEBUFFERREGIONARBPROC', 
 'PFNWGLDELETEBUFFERREGIONARBPROC', 
 'PFNWGLSAVEBUFFERREGIONARBPROC', 
 'PFNWGLRESTOREBUFFERREGIONARBPROC', 'WGL_ARB_multisample', 
 'WGL_ARB_extensions_string', 
 'wglGetExtensionsStringARB', 
 'PFNWGLGETEXTENSIONSSTRINGARBPROC', 'WGL_ARB_pixel_format', 
 'wglGetPixelFormatAttribivARB', 
 'wglGetPixelFormatAttribfvARB', 
 'wglChoosePixelFormatARB', 'PFNWGLGETPIXELFORMATATTRIBIVARBPROC', 
 'PFNWGLGETPIXELFORMATATTRIBFVARBPROC', 
 'PFNWGLCHOOSEPIXELFORMATARBPROC', 
 'WGL_ARB_make_current_read', 'wglMakeContextCurrentARB', 
 'wglGetCurrentReadDCARB', 
 'PFNWGLMAKECONTEXTCURRENTARBPROC', 
 'PFNWGLGETCURRENTREADDCARBPROC', 'WGL_ARB_pbuffer', 
 'wglCreatePbufferARB', 
 'wglGetPbufferDCARB', 'wglReleasePbufferDCARB', 'wglDestroyPbufferARB', 
 'wglQueryPbufferARB', 
 'PFNWGLCREATEPBUFFERARBPROC', 
 'PFNWGLGETPBUFFERDCARBPROC', 'PFNWGLRELEASEPBUFFERDCARBPROC', 
 'PFNWGLDESTROYPBUFFERARBPROC', 
 'PFNWGLQUERYPBUFFERARBPROC', 
 'WGL_ARB_render_texture', 'wglBindTexImageARB', 
 'wglReleaseTexImageARB', 
 'wglSetPbufferAttribARB', 'PFNWGLBINDTEXIMAGEARBPROC', 
 'PFNWGLRELEASETEXIMAGEARBPROC', 
 'PFNWGLSETPBUFFERATTRIBARBPROC', 
 'WGL_ARB_pixel_format_float', 'WGL_ARB_create_context', 
 'wglCreateContextAttribsARB', 
 'PFNWGLCREATECONTEXTATTRIBSARBPROC', 
 'WGL_EXT_display_color_table', 'wglCreateDisplayColorTableEXT', 
 'wglLoadDisplayColorTableEXT', 
 'wglBindDisplayColorTableEXT', 
 'wglDestroyDisplayColorTableEXT', 'PFNWGLCREATEDISPLAYCOLORTABLEEXTPROC', 
 'PFNWGLLOADDISPLAYCOLORTABLEEXTPROC', 
 'PFNWGLBINDDISPLAYCOLORTABLEEXTPROC', 
 'PFNWGLDESTROYDISPLAYCOLORTABLEEXTPROC', 
 'WGL_EXT_extensions_string', 
 'wglGetExtensionsStringEXT', 'PFNWGLGETEXTENSIONSSTRINGEXTPROC', 
 'WGL_EXT_make_current_read', 
 'wglMakeContextCurrentEXT', 
 'wglGetCurrentReadDCEXT', 'PFNWGLMAKECONTEXTCURRENTEXTPROC', 
 'PFNWGLGETCURRENTREADDCEXTPROC', 
 'WGL_EXT_pbuffer', 'wglCreatePbufferEXT', 
 'wglGetPbufferDCEXT', 'wglReleasePbufferDCEXT', 
 'wglDestroyPbufferEXT', 
 'wglQueryPbufferEXT', 'PFNWGLCREATEPBUFFEREXTPROC', 
 'PFNWGLGETPBUFFERDCEXTPROC', 
 'PFNWGLRELEASEPBUFFERDCEXTPROC', 
 'PFNWGLDESTROYPBUFFEREXTPROC', 'PFNWGLQUERYPBUFFEREXTPROC', 
 'WGL_EXT_pixel_format', 
 'wglGetPixelFormatAttribivEXT', 
 'wglGetPixelFormatAttribfvEXT', 'wglChoosePixelFormatEXT', 
 'PFNWGLGETPIXELFORMATATTRIBIVEXTPROC', 
 'PFNWGLGETPIXELFORMATATTRIBFVEXTPROC', 
 'PFNWGLCHOOSEPIXELFORMATEXTPROC', 
 'WGL_EXT_swap_control', 
 'wglSwapIntervalEXT', 'wglGetSwapIntervalEXT', 'PFNWGLSWAPINTERVALEXTPROC', 
 'PFNWGLGETSWAPINTERVALEXTPROC', 
 'WGL_EXT_depth_float', 
 'WGL_NV_vertex_array_range', 'wglAllocateMemoryNV', 
 'wglFreeMemoryNV', 
 'PFNWGLALLOCATEMEMORYNVPROC', 'PFNWGLFREEMEMORYNVPROC', 
 'WGL_3DFX_multisample', 
 'WGL_EXT_multisample', 'WGL_OML_sync_control', 
 'wglGetSyncValuesOML', 'wglGetMscRateOML', 
 'wglSwapBuffersMscOML', 
 'wglSwapLayerBuffersMscOML', 'wglWaitForMscOML', 
 'wglWaitForSbcOML', 
 'PFNWGLGETSYNCVALUESOMLPROC', 'PFNWGLGETMSCRATEOMLPROC', 
 'PFNWGLSWAPBUFFERSMSCOMLPROC', 
 'PFNWGLSWAPLAYERBUFFERSMSCOMLPROC', 
 'PFNWGLWAITFORMSCOMLPROC', 'PFNWGLWAITFORSBCOMLPROC', 
 'WGL_I3D_digital_video_control', 
 'wglGetDigitalVideoParametersI3D', 
 'wglSetDigitalVideoParametersI3D', 'PFNWGLGETDIGITALVIDEOPARAMETERSI3DPROC', 
 'PFNWGLSETDIGITALVIDEOPARAMETERSI3DPROC', 
 'WGL_I3D_gamma', 
 'wglGetGammaTableParametersI3D', 'wglSetGammaTableParametersI3D', 
 'wglGetGammaTableI3D', 
 'wglSetGammaTableI3D', 
 'PFNWGLGETGAMMATABLEPARAMETERSI3DPROC', 
 'PFNWGLSETGAMMATABLEPARAMETERSI3DPROC', 
 'PFNWGLGETGAMMATABLEI3DPROC', 
 'PFNWGLSETGAMMATABLEI3DPROC', 'WGL_I3D_genlock', 
 'wglEnableGenlockI3D', 
 'wglDisableGenlockI3D', 'wglIsEnabledGenlockI3D', 
 'wglGenlockSourceI3D', 
 'wglGetGenlockSourceI3D', 'wglGenlockSourceEdgeI3D', 
 'wglGetGenlockSourceEdgeI3D', 
 'wglGenlockSampleRateI3D', 
 'wglGetGenlockSampleRateI3D', 'wglGenlockSourceDelayI3D', 
 'wglGetGenlockSourceDelayI3D', 
 'wglQueryGenlockMaxSourceDelayI3D', 
 'PFNWGLENABLEGENLOCKI3DPROC', 'PFNWGLDISABLEGENLOCKI3DPROC', 
 'PFNWGLISENABLEDGENLOCKI3DPROC', 
 'PFNWGLGENLOCKSOURCEI3DPROC', 
 'PFNWGLGETGENLOCKSOURCEI3DPROC', 'PFNWGLGENLOCKSOURCEEDGEI3DPROC', 
 'PFNWGLGETGENLOCKSOURCEEDGEI3DPROC', 
 'PFNWGLGENLOCKSAMPLERATEI3DPROC', 
 'PFNWGLGETGENLOCKSAMPLERATEI3DPROC', 'PFNWGLGENLOCKSOURCEDELAYI3DPROC', 
 'PFNWGLGETGENLOCKSOURCEDELAYI3DPROC', 
 'PFNWGLQUERYGENLOCKMAXSOURCEDELAYI3DPROC', 
 'WGL_I3D_image_buffer', 
 'wglCreateImageBufferI3D', 'wglDestroyImageBufferI3D', 
 'wglAssociateImageBufferEventsI3D', 
 'wglReleaseImageBufferEventsI3D', 
 'PFNWGLCREATEIMAGEBUFFERI3DPROC', 'PFNWGLDESTROYIMAGEBUFFERI3DPROC', 
 'PFNWGLASSOCIATEIMAGEBUFFEREVENTSI3DPROC', 
 'PFNWGLRELEASEIMAGEBUFFEREVENTSI3DPROC', 
 'WGL_I3D_swap_frame_lock', 
 'wglEnableFrameLockI3D', 'wglDisableFrameLockI3D', 
 'wglIsEnabledFrameLockI3D', 
 'wglQueryFrameLockMasterI3D', 'PFNWGLENABLEFRAMELOCKI3DPROC', 
 'PFNWGLDISABLEFRAMELOCKI3DPROC', 
 'PFNWGLISENABLEDFRAMELOCKI3DPROC', 
 'PFNWGLQUERYFRAMELOCKMASTERI3DPROC', 'WGL_I3D_swap_frame_usage', 
 'wglGetFrameUsageI3D', 
 'wglBeginFrameTrackingI3D', 'wglEndFrameTrackingI3D', 
 'wglQueryFrameTrackingI3D', 
 'PFNWGLGETFRAMEUSAGEI3DPROC', 
 'PFNWGLBEGINFRAMETRACKINGI3DPROC', 'PFNWGLENDFRAMETRACKINGI3DPROC', 
 'PFNWGLQUERYFRAMETRACKINGI3DPROC', 
 'WGL_ATI_pixel_format_float', 
 'WGL_NV_float_buffer', 'WGL_EXT_pixel_format_packed_float', 
 'WGL_EXT_framebuffer_sRGB', 
 'WGL_NV_present_video', 
 'wglEnumerateVideoDevicesNV', 'wglBindVideoDeviceNV', 
 'wglQueryCurrentContextNV', 
 'PFNWGLENUMERATEVIDEODEVICESNVPROC', 
 'PFNWGLBINDVIDEODEVICENVPROC', 'PFNWGLQUERYCURRENTCONTEXTNVPROC', 
 'WGL_NV_video_out', 
 'wglGetVideoDeviceNV', 'wglReleaseVideoDeviceNV', 
 'wglBindVideoImageNV', 
 'wglReleaseVideoImageNV', 'wglSendPbufferToVideoNV', 
 'wglGetVideoInfoNV', 
 'PFNWGLGETVIDEODEVICENVPROC', 
 'PFNWGLRELEASEVIDEODEVICENVPROC', 'PFNWGLBINDVIDEOIMAGENVPROC', 
 'PFNWGLRELEASEVIDEOIMAGENVPROC', 
 'PFNWGLSENDPBUFFERTOVIDEONVPROC', 
 'PFNWGLGETVIDEOINFONVPROC', 'WGL_NV_swap_group', 
 'wglJoinSwapGroupNV', 
 'wglBindSwapBarrierNV', 'wglQuerySwapGroupNV', 'wglQueryMaxSwapGroupsNV', 
 'wglQueryFrameCountNV', 
 'wglResetFrameCountNV', 'PFNWGLJOINSWAPGROUPNVPROC', 
 'PFNWGLBINDSWAPBARRIERNVPROC', 
 'PFNWGLQUERYSWAPGROUPNVPROC', 
 'PFNWGLQUERYMAXSWAPGROUPSNVPROC', 'PFNWGLQUERYFRAMECOUNTNVPROC', 
 'PFNWGLRESETFRAMECOUNTNVPROC', 
 'WGL_NV_gpu_affinity', 'wglEnumGpusNV', 
 'wglEnumGpuDevicesNV', 'wglCreateAffinityDCNV', 
 'wglEnumGpusFromAffinityDCNV', 
 'wglDeleteDCNV', 'PFNWGLENUMGPUSNVPROC', 
 'PFNWGLENUMGPUDEVICESNVPROC', 
 'PFNWGLCREATEAFFINITYDCNVPROC', 'PFNWGLENUMGPUSFROMAFFINITYDCNVPROC', 
 'PFNWGLDELETEDCNVPROC']
# okay decompiling out\pyglet.gl.wglext_arb.pyc
