# uncompyle6 version 3.9.0
# Python bytecode version base 2.7 (62211)
# Decompiled from: Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)]
# Embedded file name: C:\TeamCity\buildAgent\work\dc8eb0b1d2cf198a\Main\client\standalone\build\pyi.win32\run_obfuscated\out00-PYZ.pyz\playlists.mapinfo
map_info = {'Alcatraz': {'max_players': 32, 'demo': False, 'release': True, 'classic': False, 'mafia': True, 'invalid_modes': ['dem', 'dia', 'tut', 'ugc']}, 'AncientEgypt': {'max_players': 32, 'demo': False, 'release': True, 'classic': False, 'mafia': False, 'invalid_modes': ['ctf', 'dem', 'tut', 'ugc']}, 'ArcticBase': {'max_players': 32, 'demo': False, 'release': True, 'classic': False, 'mafia': False, 'invalid_modes': ['ctf', 'dem', 'mh', 'tc', 'tut', 'ugc']}, 'Atlantis': {'max_players': 32, 'demo': False, 'release': True, 'classic': False, 'mafia': False, 'invalid_modes': ['tut', 'ugc']}, 'BlockNess': {'max_players': 24, 'demo': False, 'release': True, 'classic': False, 'mafia': False, 'invalid_modes': ['tut', 'ugc']}, 'BranCastle': {'max_players': 32, 'demo': False, 'release': True, 'classic': False, 'mafia': False, 'invalid_modes': ['ctf', 'dem', 'oc', 'tdm', 'vip', 'tut', 'ugc']}, 'CastleWars': {'max_players': 32, 'demo': False, 'release': True, 'classic': False, 'mafia': False, 'invalid_modes': ['oc', 'tut', 'ugc']}, 'CityOfChicago': {'max_players': 32, 'demo': False, 'release': True, 'classic': False, 'mafia': True, 'invalid_modes': ['dia', 'oc', 'tut', 'ugc']}, 'Crossroads': {'max_players': 32, 'demo': False, 'release': True, 'classic': True, 'mafia': False, 'invalid_modes': ['dia', 'tut', 'ugc']}, 'DoubleDragon': {'max_players': 32, 'demo': False, 'release': True, 'classic': False, 'mafia': False, 'invalid_modes': ['oc', 'tut', 'ugc']}, 'DragonIsland': {'max_players': 16, 'demo': False, 'release': True, 'classic': False, 'mafia': False, 'invalid_modes': ['ctf', 'tut', 'ugc']}, 'Frontier': {'max_players': 32, 'demo': False, 'release': True, 'classic': False, 'mafia': False, 'invalid_modes': ['ctf', 'tut', 'ugc']}, 'GreatWall': {'max_players': 32, 'demo': False, 'release': True, 'classic': False, 'mafia': False, 'invalid_modes': ['ctf', 'dem', 'tut', 'ugc']}, 'Hiesville': {'max_players': 32, 'demo': True, 'release': True, 'classic': True, 'mafia': False, 'invalid_modes': ['dem', 'tut', 'ugc']}, 'Invasion': {'max_players': 32, 'demo': False, 'release': True, 'classic': False, 'mafia': False, 'invalid_modes': ['dem', 'dia', 'tut', 'ugc']}, 'London': {'max_players': 20, 'demo': False, 'release': True, 'classic': False, 'mafia': False, 'invalid_modes': ['ctf', 'dem', 'tut', 'ugc']}, 'LunarBase': {'max_players': 20, 'demo': False, 'release': True, 'classic': False, 'mafia': False, 'invalid_modes': ['ctf', 'zom', 'tut', 'ugc']}, 'MayanJungle': {'max_players': 32, 'demo': False, 'release': True, 'classic': False, 'mafia': False, 'invalid_modes': ['ctf', 'dem', 'tut', 'ugc']}, 'SpookyMansion': {'max_players': 24, 'demo': False, 'release': True, 'classic': False, 'mafia': False, 'invalid_modes': ['ctf', 'dem', 'tut', 'ugc']}, 'TheColosseum': {'max_players': 32, 'demo': False, 'release': True, 'classic': False, 'mafia': False, 'invalid_modes': ['ctf', 'dem', 'tut', 'ugc']}, 'TokyoNeon': {'max_players': 32, 'demo': False, 'release': True, 'classic': False, 'mafia': False, 'invalid_modes': ['mh', 'oc', 'tc', 'tut', 'ugc']}, 'ToTheBridge': {'max_players': 32, 'demo': False, 'release': True, 'classic': True, 'mafia': False, 'invalid_modes': ['tut', 'ugc']}, 'Trenches': {'max_players': 32, 'demo': True, 'release': True, 'classic': True, 'mafia': False, 'invalid_modes': ['dem', 'oc', 'tut', 'ugc']}, 'WinterValley': {'max_players': 32, 'demo': False, 'release': True, 'classic': True, 'mafia': False, 'invalid_modes': ['dem', 'tut', 'ugc']}, 'WW1': {'max_players': 32, 'demo': False, 'release': True, 'classic': True, 'mafia': False, 'invalid_modes': ['tut', 'ugc']}, 'Classic': {'max_players': 32, 'demo': False, 'release': True, 'classic': True, 'mafia': False, 'invalid_modes': ['dem', 'dia', 'mh', 'oc', 'tc', 'tut', 'ugc']}, 'Training': {'max_players': 12, 'demo': True, 'release': True, 'classic': False, 'mafia': False, 'invalid_modes': ['ctf', 'dem', 'dia', 'mh', 'oc', 'tc', 'tdm', 
                                'vip', 'zom', 
                                'ugc']}, 'DesertBaseplate': {'max_players': 12, 'demo': False, 'release': True, 'classic': False, 'mafia': False, 'invalid_modes': ['ctf', 'dem', 'dia', 'mh', 'oc', 'tc', 
                                       'tdm', 
                                       'vip', 
                                       'zom', 
                                       'tut']}, 'LunarBaseplate': {'max_players': 12, 'demo': False, 'release': True, 'classic': False, 'mafia': False, 'invalid_modes': ['ctf', 'dem', 'dia', 'mh', 'oc', 'tc', 
                                      'tdm', 
                                      'vip', 
                                      'zom', 
                                      'tut']}, 'MountainBaseplate': {'max_players': 12, 'demo': False, 'release': True, 'classic': False, 'mafia': False, 'invalid_modes': ['ctf', 'dem', 'dia', 'mh', 'oc', 'tc', 
                                         'tdm', 
                                         'vip', 
                                         'zom', 
                                         'tut']}, 'GrasslandBaseplate': {'max_players': 12, 'demo': False, 'release': True, 'classic': False, 'mafia': False, 'invalid_modes': ['ctf', 'dem', 'dia', 'mh', 'oc', 'tc', 
                                          'tdm', 
                                          'vip', 
                                          'zom', 
                                          'tut']}, 'TempleBaseplate': {'max_players': 12, 'demo': False, 'release': True, 'classic': False, 'mafia': False, 'invalid_modes': ['ctf', 'dem', 'dia', 'mh', 'oc', 'tc', 
                                       'tdm', 
                                       'vip', 
                                       'zom', 
                                       'tut']}, 'UrbanBaseplate': {'max_players': 12, 'demo': False, 'release': True, 'classic': False, 'mafia': False, 'invalid_modes': ['ctf', 'dem', 'dia', 'mh', 'oc', 'tc', 
                                      'tdm', 
                                      'vip', 
                                      'zom', 
                                      'tut']}, 'MarshBaseplate': {'max_players': 12, 'demo': False, 'release': True, 'classic': False, 'mafia': False, 'invalid_modes': ['ctf', 'dem', 'dia', 'mh', 'oc', 'tc', 
                                      'tdm', 
                                      'vip', 
                                      'zom', 
                                      'tut']}, 'SnowyBaseplate': {'max_players': 12, 'demo': False, 'release': True, 'classic': False, 'mafia': False, 'invalid_modes': ['ctf', 'dem', 'dia', 'mh', 'oc', 'tc', 
                                      'tdm', 
                                      'vip', 
                                      'zom', 
                                      'tut']}, 'WaterBaseplate': {'max_players': 12, 'demo': False, 'release': True, 'classic': False, 'mafia': False, 'invalid_modes': ['ctf', 'dem', 'dia', 'mh', 'oc', 'tc', 
                                      'tdm', 
                                      'vip', 
                                      'zom', 
                                      'tut']}}
# okay decompiling out\playlists.mapinfo.pyc
